// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBookingPlatform.Infrastructure.Database;

#nullable disable

namespace TravelBookingPlatform.Migrations
{
    [DbContext(typeof(TravelBookingPlatformDbContext))]
    [Migration("20240221191348_PaymentTransactionTableSet")]
    partial class PaymentTransactionTableSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Status = "Confirmed",
                            TotalPrice = 150m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            Status = "Confirmed",
                            TotalPrice = 200m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            Status = "Confirmed",
                            TotalPrice = 180m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CheckInDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Status = "Confirmed",
                            TotalPrice = 120m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CheckInDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Status = "Confirmed",
                            TotalPrice = 250m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Country 1",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 1",
                            PostOffice = "PostOffice 1",
                            ThumbnailImageUrl = "/images/city1_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Country 2",
                            CreatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 2",
                            PostOffice = "PostOffice 2",
                            ThumbnailImageUrl = "/images/city2_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Country 3",
                            CreatedAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 3",
                            PostOffice = "PostOffice 3",
                            ThumbnailImageUrl = "/images/city3_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Country 4",
                            CreatedAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 4",
                            PostOffice = "PostOffice 4",
                            ThumbnailImageUrl = "/images/city4_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Country 5",
                            CreatedAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 5",
                            PostOffice = "PostOffice 5",
                            ThumbnailImageUrl = "/images/city5_thumbnail.jpg"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.FeaturedDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("FeaturedDeals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = 150m,
                            OriginalPrice = 200m,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = 200m,
                            OriginalPrice = 250m,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = 150m,
                            OriginalPrice = 180m,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = 120m,
                            OriginalPrice = 150m,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = 250m,
                            OriginalPrice = 300m,
                            RoomId = 5
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.FeaturedDealView", b =>
                {
                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FeaturedDealId")
                        .HasColumnType("int");

                    b.Property<string>("HotelLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoomThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("FeaturedDealView", (string)null);
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StarRating")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location 1",
                            Name = "Hotel 1",
                            Owner = "Owner 1",
                            StarRating = 3,
                            ThumbnailImageUrl = "/images/hotel1_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location 2",
                            Name = "Hotel 2",
                            Owner = "Owner 2",
                            StarRating = 4,
                            ThumbnailImageUrl = "/images/hotel2_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CreatedAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location 3",
                            Name = "Hotel 3",
                            Owner = "Owner 3",
                            StarRating = 5,
                            ThumbnailImageUrl = "/images/hotel3_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            CreatedAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location 4",
                            Name = "Hotel 4",
                            Owner = "Owner 4",
                            StarRating = 3,
                            ThumbnailImageUrl = "/images/hotel4_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            CreatedAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Location 5",
                            Name = "Hotel 5",
                            Owner = "Owner 5",
                            StarRating = 4,
                            ThumbnailImageUrl = "/images/hotel5_thumbnail.jpg"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = 1,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            EntityId = 1,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            EntityId = 2,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            EntityId = 2,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            EntityId = 3,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            EntityId = 3,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            EntityId = 4,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            EntityId = 4,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            EntityId = 5,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            EntityId = 5,
                            ImageType = 0,
                            ImageUrl = "/images/hotel1_image10.jpg"
                        },
                        new
                        {
                            Id = 11,
                            EntityId = 1,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            EntityId = 1,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image2.jpg"
                        },
                        new
                        {
                            Id = 13,
                            EntityId = 2,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image3.jpg"
                        },
                        new
                        {
                            Id = 14,
                            EntityId = 2,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image4.jpg"
                        },
                        new
                        {
                            Id = 15,
                            EntityId = 3,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image5.jpg"
                        },
                        new
                        {
                            Id = 16,
                            EntityId = 3,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image6.jpg"
                        },
                        new
                        {
                            Id = 17,
                            EntityId = 4,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image7.jpg"
                        },
                        new
                        {
                            Id = 18,
                            EntityId = 5,
                            ImageType = 1,
                            ImageUrl = "/images/room1_image8.jpg"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.RecentlyVisitedHotelView", b =>
                {
                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StarRating")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserVisitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView("RecentlyVisitedHotels", (string)null);
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ChildCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultCapacity = 2,
                            Availability = true,
                            ChildCapacity = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Number = 101,
                            Price = 200m,
                            ThumbnailImageUrl = "/images/room1_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AdultCapacity = 3,
                            Availability = true,
                            ChildCapacity = 2,
                            CreatedAt = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Number = 102,
                            Price = 150m,
                            ThumbnailImageUrl = "/images/room2_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AdultCapacity = 2,
                            Availability = true,
                            ChildCapacity = 1,
                            CreatedAt = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Number = 201,
                            Price = 180m,
                            ThumbnailImageUrl = "/images/room3_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AdultCapacity = 4,
                            Availability = true,
                            ChildCapacity = 2,
                            CreatedAt = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Number = 202,
                            Price = 150m,
                            ThumbnailImageUrl = "/images/room4_thumbnail.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AdultCapacity = 2,
                            Availability = true,
                            ChildCapacity = 1,
                            CreatedAt = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            Number = 301,
                            Price = 300m,
                            ThumbnailImageUrl = "/images/room5_thumbnail.jpg"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            PasswordHash = "hashedPassword1",
                            RoleId = 1,
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            PasswordHash = "hashedPassword2",
                            RoleId = 1,
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.com",
                            PasswordHash = "hashedPassword3",
                            RoleId = 1,
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@example.com",
                            PasswordHash = "hashedPassword4",
                            RoleId = 1,
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@example.com",
                            PasswordHash = "hashedPassword5",
                            RoleId = 1,
                            Username = "user5"
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.UserVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("UserVisits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            UserId = 1,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 2,
                            UserId = 1,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 3,
                            UserId = 1,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 4,
                            UserId = 1,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 5,
                            UserId = 1,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 1,
                            UserId = 2,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 2,
                            UserId = 2,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 3,
                            UserId = 2,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 4,
                            UserId = 2,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 5,
                            UserId = 2,
                            VisitDateTime = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelBookingPlatform.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.FeaturedDeal", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Room", "Room")
                        .WithOne("FeaturedDeal")
                        .HasForeignKey("TravelBookingPlatform.Domain.Entities.FeaturedDeal", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Image", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("EntityId");

                    b.HasOne("TravelBookingPlatform.Domain.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("EntityId");

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Booking", "Booking")
                        .WithOne("PaymentTransaction")
                        .HasForeignKey("TravelBookingPlatform.Domain.Entities.PaymentTransaction", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Room", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.User", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.UserVisit", b =>
                {
                    b.HasOne("TravelBookingPlatform.Domain.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelBookingPlatform.Domain.Entities.User", "User")
                        .WithMany("VisitedHotels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Booking", b =>
                {
                    b.Navigation("PaymentTransaction")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FeaturedDeal")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("TravelBookingPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("VisitedHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
